#pragma once
#define SERIAL_USART_FULL_DUPLEX
#define SOFT_SERIAL_PIN A10
#define SERIAL_USART_RX_PIN A11
#define SERIAL_USART_DRIVER SD0

#define SELECT_SOFT_SERIAL_SPEED 0
#define DEBUG_MATRIX_SCAN_RATE
//#define SPLIT_WATCHDOG_ENABLE
//#define SPLIT_WATCHDOG_TIMEOUT 3000
//#    define RGB_MATRIX_LED_PROCESS_LIMIT ((70 + 4) / 5)
//#define MATRIX_UNSELECT_DRIVE_HIGH
//#define MATRIX_IO_DELAY 1
//#define GPIO_INPUT_PIN_DELAY 0
#define WAIT_US_TIMER GPTD1
//#define DISABLE_SYNC_TIMER
#define ENCODER_MAP_KEY_DELAY 1
//#define SLED1734X_I2C_TIMEOUT 200
#define SLED1734X_I2C_ADDRESS_1 SLED1734X_I2C_ADDRESS_GND
//#define SLED1734X_I2C_ADDRESS_2 SLED1734X_I2C_ADDRESS_GND
//#define RGB_MATRIX_LED_COUNT (40 + 70)
//#define SPLIT_HAND_PIN_LOW_IS_LEFT
#define I2C_DRIVER I2CD0
#define I2C1_SCL_PIN A6
#define I2C1_SDA_PIN A7
#define I2C1_OPMODE OPMODE_I2C
#define I2C1_CLOCK_SPEED 400000
#    define CORTEX_ENABLE_WFI_IDLE FALSE
