#pragma once
#define SERIAL_USART_FULL_DUPLEX
#define SOFT_SERIAL_PIN A10
#define SERIAL_USART_RX_PIN A11
#define SERIAL_USART_DRIVER SD0
#define SERIAL_DEBUG
//#    define SELECT_SOFT_SERIAL_SPEED 5


