// Copyright 2025 Dimitris Mantzouranis <d3xter93@gmail.com>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
#define SERIAL_USART_FULL_DUPLEX
#define SOFT_SERIAL_PIN A10
#define SERIAL_USART_RX_PIN A11
#define SERIAL_USART_DRIVER SD0

#define MATRIX_UNSELECT_DRIVE_HIGH
#define MATRIX_IO_DELAY 1
#define GPIO_INPUT_PIN_DELAY 0
#define WAIT_US_TIMER GPTD1
#define ENCODER_MAP_KEY_DELAY 1
#define SLED1734X_I2C_ADDRESS_1 SLED1734X_I2C_ADDRESS_GND

#define I2C_DRIVER I2CD0
#define I2C1_SCL_PIN A6
#define I2C1_SDA_PIN A7
#define I2C1_OPMODE OPMODE_I2C
#define I2C1_CLOCK_SPEED 400000
#define CORTEX_ENABLE_WFI_IDLE FALSE
#define SPLIT_WATCHDOG_ENABLE

#define LED_FN_PIN A0
#define LED_MAC_PIN A2
#define LED_PC_PIN A3

#define WEAR_LEVELING_BACKING_SIZE 4096
